routes/admin.php
<?php

use App\Http\Controllers\Admin\AccountController;
use App\Http\Controllers\Admin\ApplyController;
use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CvController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\JobController;
use App\Http\Controllers\Admin\KpiController;
use App\Http\Controllers\Admin\NotifyController;
use App\Http\Controllers\Admin\SettingJobController;
use App\Http\Controllers\Admin\SettingRoleController;
use App\Http\Controllers\Admin\SettingSourceController;
use App\Http\Controllers\Admin\ShortUrlController;
use App\Http\Controllers\FullCalendarController;
use App\Models\Notify;
use App\Models\Permission;
use Illuminate\Support\Facades\Route;
use Laravel\Socialite\Facades\Socialite;

Route::controller(AuthController::class)
    ->middleware('prevent-back-history')
    ->prefix("auth")
    ->group(function () {
        Route::post('login', 'handleLogin')->name('admin.handleLogin');
        Route::post('register', 'registering')->name('admin.register');
        Route::get('redirect/{provider}', function ($provider) {
            return Socialite::driver($provider)->redirect();
        })->name('auth.redirect');
        Route::get('callback/{provider}', [AuthController::class, 'callback'])->name('auth.callback');
        Route::post('logout', 'logout')->name('admin.logout');
    });
Route::prefix('admin')
    ->middleware(['auth:sanctum', 'check.auth.user', 'prevent-back-history'])
    ->group(function () {
        Route::get('404', function () {
            return view('admin.errors.404');
        })->name('admin.errors');
        Route::resource('dashboard', DashboardController::class)->only([
            'index'
        ]);
        Route::resource('accounts', AccountController::class)->only([
            'index', 'show', 'update'
        ]);
        Route::post('accounts/status/{id}', [AccountController::class, 'changeStatus'])->name('account.status');
        Route::controller(SettingJobController::class)
            ->prefix('setting-job')
            ->middleware('check.permission.user:' . Permission::PERMISSION_ID['SETTING-JOB'])
            ->group(function () {
                // level
                Route::get('levels', 'showLevel')->name('admin.level.show');
                // salary
                Route::get('salaries', 'showSalary')->name('admin.salary.show');
                // skill
                Route::get('skills', 'showSkill')->name('admin.skill.show');
                // jobs
            });
        Route::resource('jobs', JobController::class)->except([
            'index', 'show'
        ])->middleware('check.permission.user:' . Permission::PERMISSION_ID['CRUD-JOB']);
        Route::get('jobs', [JobController::class, 'index'])
            ->middleware('check.permission.user:' . Permission::PERMISSION_ID['SHOW-JOB'])
            ->name('jobs.index');
        Route::get('jobs/{job}', [JobController::class, 'show'])
            ->middleware('check.permission.user:' . Permission::PERMISSION_ID['SHOW-JOB'])
            ->name('jobs.show');
        Route::post('jobs/status/{id}', [JobController::class, 'changeStatus'])
            ->middleware('check.permission.user:' . Permission::PERMISSION_ID['CRUD-JOB'])
            ->name('jobs.status');
        Route::resource('settings', SettingRoleController::class)->only([
            'index'
        ])->middleware('check.permission.user:' . Permission::PERMISSION_ID['PERMISSION'] . '|' . Permission::PERMISSION_ID['SETTING-KPI'] . '|' . Permission::PERMISSION_ID['BONUS']);
        Route::resource('categories', CategoryController::class);
        Route::resource('blogs', BlogController::class);
        Route::post('shortUrl', [ShortUrlController::class, 'store'])->name('store.shortUrl');

        //cv
        Route::resource('cv', CvController::class)->only('index');

        Route::resource('sources', SettingSourceController::class)->only(['index', 'store', 'update', 'destroy']);
        Route::get('list-kpi', [KpiController::class, 'index'])->name('list-kpi.index');
        Route::get('fullcalendar',[FullCalendarController::class, 'index'])->name('fullcalendar.index');
        Route::get('getfullcalendar',[FullCalendarController::class, 'showCalendar'])->name('fullcalendar.showCalendar');
    });
//apply
Route::resource('apply', ApplyController::class)->only('store');


Route::get('admin/tesing', function () {
    return view('welcome');
})->name('notify');

//fullcalender

routes/web.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\JobController;
use App\Http\Controllers\Admin\SearchController;
use App\Http\Controllers\Admin\ShortUrlController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('prevent-back-history')
    ->group(function () {
        Route::get('/', [JobController::class, 'getAll'])->name('jobs');
        Route::get('/login', [AuthController::class, 'login'])->name('admin.login');
        Route::get('/tuyen-dung/{slug}', [JobController::class, 'showJobDetailClient'])->name('client.job.detail');
        Route::get('/lien-he', function () {
            return view('client.contacts.index', []);
        })->name('contact');
        Route::get('/nguoi-hachinet', function () {
            return view('client.faq.index', []);
        })->name('faq');
        Route::get('/tin-tuc', [BlogController::class, 'getAll'])->name('about');
        Route::get('/tin-tuc/{slug}', [BlogController::class, 'getCategoryBlog'])->name('abouts');
        Route::get('/blog/{slug}', [BlogController::class, 'showBlogDetailClient'])->name('blog.detail');
        Route::post('/contactStore', [ContactController::class, 'store'])->name('client.contact.store');
        Route::post('/contactEmail', [ContactController::class, 'store_email'])->name('client.contact.email');
        Route::post('/contactSubscribe', [ContactController::class, 'store'])->name('client.contact.subscribe');
        Route::get('/404', function () {
            return view('errors.404');
        })->name('404');
        Route::get('/tuyen-dung-lap-trinh-tai/{address?}/{skill?}', [SearchController::class, 'searchAll'])->name('client.findjob.all');
        Route::get('/tuyen-dung-lap-trinh/{skill?}', [SearchController::class, 'searchSkill'])->name('client.findjob.skill');
        Route::post('/tuyen-dung-lap-trinh', [SearchController::class, 'search'])->name('client.findjob.url');
        Route::get('/filterBlog/{id}', [BlogController::class, 'filterBlogsList'])->name('blog.filterBlog');
        // luôn luôn phải để url này cuối cùng để không bị ghi đè lên cách url khác
        Route::get('/{code}', [ShortUrlController::class, 'shortenLink']);
    });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Category extends Model
{
    use HasFactory, Sluggable;

    protected $fillable = [
        'name',
        'slug',
        'description',
        'image_path'
    ];

    const CATEGORY_STATUS = [
        'ACTIVE' => 'active',
        'INACTIVE' => 'inactive',
    ];

    public $timestamps = true;

     /**
    * Return the created_at configuration array for this model.
    *
    * @return array
    */
    protected $casts = [
        'created_at' => 'date:d-m-Y',
        'updated_at' => 'date:d-m-Y'
    ];

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'name',
            ],
        ];
    }

    public function blogs()
    {
        return $this->hasMany(Blog::class, 'category_id');
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{

    public function __construct(Category $category, CategoryService $categoryService)
    {
        $this->category = $category;
        $this->categoryService = $categoryService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::get();
        return view('admin.categories.index', [
            'categories' => $categories,
        ]);
    }

    public function list()
    {
        try {
            $categories = $this->category->get();
            foreach ($categories as $each) {
                if ($each->image_path != null) {
                    $each->image_path = url('/' . 'storage/' . $each->image_path);
                }
            }
            return response()->json(['data' => $categories], 200);
        } catch (\Throwable $th) {
            return response()->json(['message' => config('const.not_content')], 403);
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        try {
            $data = $request->all();
            unset($data['_token']);
            if ($request->hasFile('fileImage')) {
                $images = $request->file('fileImage');
                $path = Storage::disk('public')->put('imageCategories', $images);
                $data['image_path'] = $path;
            }
            $categories = $this->categoryService->create($data);
            return response()->json([
                'category' => $categories,
            ], 200);
        } catch (\Throwable $th) {
            return response()->json(['message' => config('const.not_content')], 403);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('admin.categories.index', [
            'count' => $this->category->count()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $categories = $this->category->findOrFail($id);
            if ($categories->image_path != null) {
                $categories->image_path = url('/' . 'storage/' . $categories->image_path);
            }
            return response()->json([
                'category' => $categories
            ], 200);
        } catch (\Throwable $th) {
            return response()->json(['message' => config('const.not_content')], 403);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $data = $request->all();
            $data['id'] = $id;
            $data['fileImage'] = $request->file('fileImage');
            $data['checkFile'] = $request->hasFile('fileImage');
            unset($data['_method'], $data['_token']);
            $categories = $this->categoryService->update($data);
            return response()->json([
                'category' => $categories,
            ], 200);
        } catch (\Throwable $th) {
            return response()->json(['message' => config('const.not_content')], 403);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $categories = Category::findOrFail($id);
            if ($categories->image_path != null) {
                if (Storage::disk('public')->exists($categories->image_path)) {
                    Storage::disk('public')->delete($categories->image_path);
                }
            }
            $categories->delete($id);
            return response()->json([], 200);
        } catch (\Throwable $th) {
            return response()->json(['message' => config('const.not_content')], 403);
        }
    }
}

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.layoutAdmin')
@section('title', 'Danh sách danh mục')
@push('css')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ asset('/assets/css/datatable.css') }}">
    <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.12.1/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/date-1.1.2/fc-4.1.0/fh-3.2.3/r-2.3.0/rg-1.2.0/sc-2.0.6/sb-1.3.3/sl-1.4.0/datatables.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        tbody tr td:nth-child(2),
        th {
            text-align: center !important;
        }
        .dataTables_wrapper .dataTables_paginate .paginate_button {
            padding: 0.2em 0.8em !important;
        }
        div#datatable_paginate {
            margin: 16px 0px 30px;
        }
    </style>
@endpush
@section('content')
    <!-- ============================================================== -->
    <!-- Start Content here -->
    <!-- ============================================================== -->
    <div class="content datatable_custom_content">
        <div class="row">
            <div class="col-md-12" style="padding-right: 0px;">
                <h3 style="padding: 10px 0px;"><b>Danh sách danh mục</b></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 m-l-0 m-r-0">
                <div class="widget bg-none m-l-0 m-r-0" style="border-radius: 4px!important; padding-right: 0 !important; padding-left: 0 !important;">
                    <div class="widget-content">
                        <div class="">
                            <table class="table table-hover yajra-datatable" id="datatable">
                                <thead>
                                    <tr>
                                        {{-- <th><i style="margin-right: 3px;"></i>*</th> --}}
                                        <th>
                                            STT</th>

                                        <th><i class="fa fa-book" style="margin-right: 3px;"></i></i>Tên danh mục</th>
                                        <th><i class="fa fa-align-justify" style="margin-right: 3px;"></i>Hoạt động
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 position-back">
                <div class="card position-relative">
                    <div class="card-body">
                        <form data-route="{{ route('categories.store') }}" id="formValidate" style="padding-top: 12px;"
                            enctype="multipart/form-data">
                            @csrf
                            <div class="mb-2 input-name">
                                <label class="form-label required">Tên danh mục</label>

                                <input type="text" name="name" id="name" value="{{ old('name') }}"
                                    class="form-control" placeholder="Nhập Tên..." />
                                <span class="text-danger alertSpan nameErr">
                                </span>
                            </div>
                            <div class="mb-2">
                                <label class="form-label required">Mô tả</label>

                                <textarea name="description" cols="30" rows="11" value="" id="description" class="form-control"
                                    placeholder="Mô tả ..."></textarea>
                                <span class="text-danger alertSpan errDes">
                                </span>
                            </div>

                            <div class="mb-3 d-flex" style="margin: 4px 0px;" style="margin: 4px 0px;">
                                <button class="btn btn-primary button" id="storeAdd">Thêm</button>
                                <button style="display: none; margin-left: 4px;;" type="button" id="button-add"
                                    class="float-right btn btn-danger">Hủy</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- End content here -->
    <!-- ============================================================== -->
@endsection
@push('js')
    <script type="text/javascript"
        src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.12.1/b-2.2.3/b-colvis-2.2.3/b-html5-2.2.3/b-print-2.2.3/date-1.1.2/fc-4.1.0/fh-3.2.3/r-2.3.0/rg-1.2.0/sc-2.0.6/sb-1.3.3/sl-1.4.0/datatables.min.js">
    </script>
    <script src="{{ asset('/assets/js/admin/categories.js') }}"></script>
    <script>
        // Data Display Code
        var table = $('#datatable').DataTable({
            ajax: "{{ route('api.categories.list') }}",
            lengthMenu: [6],
            columns: [{
                    "data": "id"
                },

                {
                    "data": "name"
                },
                {
                    "data": "id",
                    render: function(data, type, row) {
                        return `<div class="btn-group btn-group-xs">
                                    <a data-id="${row.id}" id="" data-toggle="tooltip" title="Edit" class=" button-edit"><button type="button" class="btn-custom-action"><i class="fa fa-edit"></i>&nbsp;&nbsp;Sửa</button></a><br>
                                    <a data-id="${row.id}"  id="delete" class="btn-delete" data-toggle="tooltip" title="Delete" class="action-custom button-delete"><button type="button" class="btn-custom-action"><i class="fa fa-trash-o"></i>&nbsp;&nbsp;Xóa</button></a>
                                </div>`;
                    }
                },
            ],
            "bLengthChange": false,
            sDom: 'lrtip',
            language: {
                "sProcessing": "<span class='fa-stack fa-lg text-yellow'>\n\
                            <i class='fa fa-spinner fa-spin fa-stack-2x fa-fw'></i>\n\
                       </span>&emsp;",
                "sLengthMenu": "Hiển thị _MENU_ bản ghi",
                "sZeroRecords": "Không có dữ liệu trong bảng",
                "sInfo": "",
                "sInfoEmpty": "Hiển thị 0 đến 0 trong số 0 bản ghi",
                "sInfoFiltered": "(Đã lọc từ _MAX_ bản ghi)",
                "sSearch": "",
                "oPaginate": {
                    "sFirst": "Đầu trang",
                    "sLast": "Cuối trang",
                    "sNext": "»",
                    "sPrevious": "«"
                },
                searchPlaceholder: "Tên kỹ năng",
            }
        });
        table.on('order.dt search.dt', function() {
            let i = 1;

            table.cells(null, 0).every(function(cell) {
                this.data(i++);
            });
        }).draw();
    </script>
@endpush